### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by vikash** [kubitron/redmine_git_hosting#74]
I have been trying to install on ubuntu 12.04. Redmine was upgraded successfully from 1.0 to 1.3. I don't know if it's relevant but earlier I was using gitosis and just shifted to gitolite. 

On running "rake db:migrate_plugins RAILS_ENV=production" - I am getting errors as follows: 

```
rake aborted!
An error has occurred, all later migrations canceled:

Mysql::Error: Key column 'identifier' doesn't exist in table: CREATE  INDEX `index_repositories_on_identifier` ON `repositories` (`identifier`)

Tasks: TOP => db:migrate_plugins
```

I do not have much idea about rails. So I am sorry if it's an issue at my end. 

UPDATE: 
I commented line 40/41 in  db / migrate / 20120904060609_update_multi_repo_per_project.rb and tried again. Obviously the migration was successful and it started working. However, after a while following errors were occuring when trying to access the projects:

```
ActionView::TemplateError (undefined local variable or method `identifier' for #<Repository::Git:0x7febb79064b0>) on line #13 of vendor/plugins/redmine_git_hosting/app/views/projects/_git_urls.erb:
```

Do I need to add the identifier column manually? How can it be fixed.

**Comment by greizgh** [comment]
The current master head is compatible with redmine 1.4. Perhaps last changes have broken compatibility with versions <1.4.
You could try to fetch revision tagged 0.4.6x, which is announced to work with redmine 1.3

**Comment by vikash** [comment]
I tried 0.4.6x. Now, unlike before, /projects/project-name URL started working. I can see the diffs of change sets. But, /projects/project-name/repository still does not work. This is the error:

```
Processing RepositoriesController#show (for 100.100.100.100 at 2012-10-06 09:02:22) [GET]
  Parameters: {"action"=>"show", "controller"=>"repositories", "id"=>"project-name"}
git: error during get default branch: unknown attribute: proj_identifier

```

Do you plan to support redmine 1.3.2 - as it is the packaged version for Ubuntu 12.04 LTS.

UPDATE:

Also, the project setting page is having errors:

```
Processing ProjectsController#settings (for 100.100.100.100 at 2012-10-06 09:09:21) [GET]
  Parameters: {"action"=>"settings", "controller"=>"projects", "id"=>"project-name"}
Fetching changes from gitolite-admin repository to /tmp/redmine_git_hosting/git/gitolite-admin
Our hook is already installed
Rendering template within layouts/base
Rendering projects/settings

ActionView::TemplateError (Mysql::Error: Unknown column 'repository_post_receive_urls.project_id' in 'where clause': SELECT count(*) AS count_all FROM `repository_post_receive_urls` WHERE (`repository_post_receive_urls`.project_id = 1) ) on line #156 of vendor/plugins/redmine_git_hosting/app/views/projects/settings/_repository.html.erb
```

**Comment by greizgh** [comment]
Did you uninstalled branch 0.5.0x before switching to 0.4.6x? Database error make me think of a problem during migration.
Concerning support for 1.3, I can't say but I believe @kubitron is actually working on 2.0 compat.

Try to [remove the plugin](http://www.redmine.org/projects/redmine/wiki/Plugins#Uninstalling-a-plugin) before switching to another branch.

**Comment by kubitron** [comment]
A couple of comments.  I'm out of range of laptop, but....

For now, @vikash, you are correct -- for Redmine 1.3x, comment out those two lines.  I'll fix it.

If you downgrade to 0.4.6x you have to uninstall first.  Won't work otherwise.

**Comment by kubitron** [comment]
@vikash, sorry, I was traveling.

You found a bug in the migration for the current plugin with a 1.3 installation. I fixed the migration so that it will effectively comment out those two lines if you have a 1.3 installation.

As for trying to go back to 0.4.6x from 0.5.0x, that will not work well.  I suggest that you return to the 0.5.0x version.  It should work fine with Redmine 1.3.x.  (Let me know if it doesn't, since it definitely should).  It looks like you didn't actually keep trying to work with 0.5.0x after you commented out those lines?

**Comment by kubitron** [comment]
Assuming that things end up working fine with the 0.5.0x version, let me know -- I would like to close out this bug.

**Comment by vikash** [comment]
This is what I got when trying to uninstall:

```
==  ExtendChangesetsNotifiedCia: reverting ====================================
-- remove_column(:changesets, :notified_cia)
rake aborted!
An error has occurred, all later migrations canceled:

Mysql::Error: Can't DROP 'notified_cia'; check that column/key exists: ALTER TABLE `changesets` DROP `notified_cia`
```

Ignoring this, if I switched back to 0.5.0x and try to migrate again:

```
An error has occurred, all later migrations canceled:
undefined method `notified_cia' for #<Changeset:0x7fd8dad071a8>
Tasks: TOP => db:migrate_plugins

```

**Comment by kubitron** [comment]
Um.... Uninstalling is not currently working well... (which is why I told you to just try using 0.5.0x).  Are you working on a fresh install, or do you have data in your database already?

If it is the former, I would suggest starting from a fresh install (i.e. new database, first do a "db:migrate" then a "db:migrate_plugins".  If it is the later, we can try to figure out how to fix your database.

**Comment by vikash** [comment]
I already have data. Fortunately I have a backup which contains the state just before the plugin. I will just lose few bugs added afterwards but that's okay. Will try a fresh install now and update

**Comment by kubitron** [comment]
Well, we can fix this, if you like...!

**Comment by vikash** [comment]
Starting with fresh install, still getting the same error:

```
-- add_index(:projects, [:identifier])
   -> 0.0168s
-- add_index(:repositories, [:identifier])
rake aborted!
An error has occurred, all later migrations canceled:
Mysql::Error: Key column 'identifier' doesn't exist in table: CREATE  INDEX `index_repositories_on_identifier` ON `repositories` (`identifier`)
```

So, commented out line 40/41 and 105/106 and tried everything again - migration worked, as mentioned earlier. But, while accessing project page - following error occurs:

```
Processing ProjectsController#show (for 180.151.36.170 at 2012-10-09 05:15:21) [GET]
  Parameters: {"id"=>"project-name", "action"=>"show", "controller"=>"projects"}
Rendering template within layouts/base
Rendering projects/show

ActionView::TemplateError (undefined local variable or method `identifier' for #<Repository::Git:0x7ffcd666a078>) on line #13 of vendor/plugins/redmine_git_hosting/app/views/projects/_git_urls.erb:
```

**Comment by kubitron** [comment]
Did you get the latest head of master?   This looks like you have the same bug after I fixed it.

However, I see that there is another bug still.

Could you (1) pull the testing branch.  (2) see if you can "uninstall" properly now? (3) see if you can reinstall without any bugs?  You will still have the new bug (which I will fix shortly).

**Comment by vikash** [comment]
Uninstall and reinstall works on the testing branch.

**Comment by kubitron** [comment]
Good!  Now pull the testing branch again and see if that fixes the operational bugs (sorry!)

**Comment by vikash** [comment]
Yes. The project page is working now.

**Comment by kubitron** [comment]
Sorry about the problems.  I'm going to move these commits over to the master branch.  Please change over to using master again.

Can we close out this bug?  (You can register a new bug if you find one).
