### ISSUE TITLE
fails to install on redmine 1.1

### ISSUE THREAD

**Issue by anarcat** [kubitron/redmine_git_hosting#12]
the db:migrate_plugins fails with:

```
undefined method `create' for class `ProjectsController'
```

Our install notes are here: https://wiki.koumbit.net/RedmineGitolite

**Comment by kubitron** [comment]
Ok.  Can you give me a brief summary of what it is that is the biggest thing preventing you from going to Redmine 1.2?  Is it use of a new version of Rails?...?  Also, what is the "backport" issue about?

**Comment by anarcat** [comment]
Redmine 1.2 isn't packaged for Debian, 1.3 is. It is in Debian "testing" (wheezy), but not in Debian Stable (squeeze). In order to get it down to squeeze, we do what we call a "backport", which involves recompiling the package with all the right dependencies. In the case of Redmine 1.3, we also need to backport rails, so that means a huge pile of work.

Basically, 1.2 is not an option, and 1.3 is hard right now, but coming.

**Comment by kubitron** [comment]
Um.... Backport Rails 3.x?  Redmine 1.3 works with 2.3.14 (I am using it that way at the moment).

**Comment by kubitron** [comment]
(Probably works with earlier 2.3 versions, I just keep updating to latest packages for security reasons).

**Comment by anarcat** [comment]
Debian stable has Rails 2.3.5, which Redmine 1.3 isn't compatible with, apparently. The Debian package, at least, indicates clearly that redmine requires 2.3.14 and previous experience from other porters confirmed the metadata.

**Comment by kubitron** [comment]
Ok.  I managed to put a Redmine 1.1 environment together with some effort.  I have uploaded a patch to my "testing" branch, which seems to (1) allow the plugin to work with 1.1, and (2) allow db:migrate_plugins to work.  I have to confess that I could not reproduce your actual error, so perhaps there is something else.  I have done some preliminary testing with a 1.1 version of Redmine and these fixes seem to let it work the way I expect.

Just to let you know, I grabbed a vanilla 1.1 (svn revision 4670, which seems to be what was announced tagged as 1.1.0).  I was able to run db:migrate_plugins. Now, I didn't actually run the code that way -- I downgraded a working implementation to 1.1.0 with my new patches and everything seemed to work. [I have hooked into Redmine in other ways, and didn't want to have to redo them].  

Let me know what happens.  If it works, I'll merge it into my master branch.  If not quite, I'll see what I can do.

**Comment by anarcat** [comment]
You know, I just realized that I made a mistake and have _not_ yet upgraded to 1.1 :( We are still running 1.0. So this is my mistake, sorry!! But I'm happy to learn this works with 1.1 - I will try again with the new release. Thanks a lot for the support.

**Comment by kubitron** [comment]
Well, I'm not 100% positive that it works with 1.1.  Will you be able to try it? (I know that you are working under serious constraints).  Let me know.

**Comment by anarcat** [comment]
i have just tried it out, this is the result, on the master branch:

```
root@apps:/usr/share/redmine/vendor/plugins# sudo -u redmine X_DEBIAN_SITEID=koumbit RAILS_ENV=production rake db:migrate_plugins
(in /usr/share/redmine)
rake aborted!
undefined method `sq_bin' for class `Class'

(See full trace by running task with --trace)
```

Here is the full trace.

```
/usr/lib/ruby/1.8/active_support/core_ext/module/aliasing.rb:33:in `alias_method'
/usr/lib/ruby/1.8/active_support/core_ext/module/aliasing.rb:33:in `alias_method_chain'
/usr/share/redmine/vendor/plugins/redmine_git_hosting/lib/git_hosting/patches/git_adapter_patch.rb:18:in `included'
/usr/share/redmine/vendor/plugins/redmine_git_hosting/lib/git_hosting/patches/git_adapter_patch.rb:16:in `class_eval'
/usr/share/redmine/vendor/plugins/redmine_git_hosting/lib/git_hosting/patches/git_adapter_patch.rb:16:in `included'
/usr/share/redmine/vendor/plugins/redmine_git_hosting/init.rb:65:in `include'
/usr/share/redmine/vendor/plugins/redmine_git_hosting/init.rb:65:in `send'
/usr/share/redmine/vendor/plugins/redmine_git_hosting/init.rb:65:in `evaluate_init_rb'
/usr/lib/ruby/1.8/active_support/callbacks.rb:182:in `call'
/usr/lib/ruby/1.8/active_support/callbacks.rb:182:in `evaluate_method'
/usr/lib/ruby/1.8/active_support/callbacks.rb:166:in `call'
/usr/lib/ruby/1.8/active_support/callbacks.rb:90:in `run'
/usr/lib/ruby/1.8/active_support/callbacks.rb:90:in `each'
/usr/lib/ruby/1.8/active_support/callbacks.rb:90:in `send'
/usr/lib/ruby/1.8/active_support/callbacks.rb:90:in `run'
/usr/lib/ruby/1.8/active_support/callbacks.rb:276:in `run_callbacks'
/usr/lib/ruby/1.8/action_controller/dispatcher.rb:51:in `send'
/usr/lib/ruby/1.8/action_controller/dispatcher.rb:51:in `run_prepare_callbacks'
/usr/share/redmine/config/../vendor/rails/railties/lib/initializer.rb:631:in `prepare_dispatcher'
/usr/share/redmine/config/../vendor/rails/railties/lib/initializer.rb:185:in `process'
/usr/share/redmine/config/../vendor/rails/railties/lib/initializer.rb:113:in `send'
/usr/share/redmine/config/../vendor/rails/railties/lib/initializer.rb:113:in `run'
/usr/share/redmine/config/environment.rb:61
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
/usr/lib/ruby/1.8/active_support/dependencies.rb:156:in `require'
/usr/lib/ruby/1.8/active_support/dependencies.rb:521:in `new_constants_in'
/usr/lib/ruby/1.8/active_support/dependencies.rb:156:in `require'
/usr/share/redmine/vendor/rails/railties/lib/tasks/misc.rake:4
/usr/lib/ruby/1.8/rake.rb:636:in `call'
/usr/lib/ruby/1.8/rake.rb:636:in `execute'
/usr/lib/ruby/1.8/rake.rb:631:in `each'
/usr/lib/ruby/1.8/rake.rb:631:in `execute'
/usr/lib/ruby/1.8/rake.rb:597:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:607:in `invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:604:in `each'
/usr/lib/ruby/1.8/rake.rb:604:in `invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:596:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:583:in `invoke'
/usr/lib/ruby/1.8/rake.rb:2051:in `invoke_task'
/usr/lib/ruby/1.8/rake.rb:2029:in `top_level'
/usr/lib/ruby/1.8/rake.rb:2029:in `each'
/usr/lib/ruby/1.8/rake.rb:2029:in `top_level'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:2023:in `top_level'
/usr/lib/ruby/1.8/rake.rb:2001:in `run'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1998:in `run'
/usr/bin/rake:28
```

On testing, I get this even before that error:

```
root@apps:/usr/share/redmine# sudo -u redmine LANG=C LC_ALL=C X_DEBIAN_SITEID=koumbit RAILS_ENV=production rake db:migrate_plugins
(in /usr/share/redmine)
mkdir: cannot create directory `/usr/share/redmine/vendor/plugins/redmine_git_hosting/bin': Permission denied
chmod: cannot access `/usr/share/redmine/vendor/plugins/redmine_git_hosting/bin': No such file or directory
chown: cannot access `/usr/share/redmine/vendor/plugins/redmine_git_hosting/bin': No such file or directory
mkdir: cannot create directory `/usr/share/redmine/vendor/plugins/redmine_git_hosting/bin': Permission denied
chmod: cannot access `/usr/share/redmine/vendor/plugins/redmine_git_hosting/bin': No such file or directory
chown: cannot access `/usr/share/redmine/vendor/plugins/redmine_git_hosting/bin': No such file or directory
mkdir: cannot create directory `/usr/share/redmine/vendor/plugins/redmine_git_hosting/bin': Permission denied
chmod: cannot access `/usr/share/redmine/vendor/plugins/redmine_git_hosting/bin': No such file or directory
chown: cannot access `/usr/share/redmine/vendor/plugins/redmine_git_hosting/bin': No such file or directory
mkdir: cannot create directory `/usr/share/redmine/vendor/plugins/redmine_git_hosting/bin': Permission denied
chmod: cannot access `/usr/share/redmine/vendor/plugins/redmine_git_hosting/bin': No such file or directory
chown: cannot access `/usr/share/redmine/vendor/plugins/redmine_git_hosting/bin': No such file or directory
rake aborted!
No such file or directory - /usr/share/redmine/vendor/plugins/redmine_git_hosting/bin/gitolite_admin_ssh
```

There is indeed no gitolite_admin_ssh binary in there..  After giving the permissions to the redmine users to create a subdirectory there, however, I end up in exactly the same place as on the master branch above (undefined method `sq_bin' for class`Class'). now the odd thing is that after running the migrate, the directory is still not there - is it possible that this directory is used as a temporary directory? that would seem wrong to me...

stuck again... :/ thanks for the support!

**Comment by kubitron** [comment]
I didn't change the 'master' branch yet.  As I mentioned in my post above, the fix is on the 
'testing' branch.  Does that work?

**Comment by anarcat** [comment]
As I mentionned above, I tried the testing branch, which failed in a similar way (on top of a new bug that it needs the plugin directory to be writable).

**Comment by kubitron** [comment]
Sorry -- that is what I get for looking at your response on the small screen of my phone.

Ok.  Needing the plugin directory to be writeable is actually intentional -- I use selinux and want there to be a well-defined place for the binaries to be written to that is associated with the particular plugin you are using (I have multiple instances of the plugin working with different gitolite repos). The scripts are customized to your particular installation (and run, among other things, sudo).  Originally, the binaries were put in the /tmp directory, which is a bit problematic for other reasons.  I may make this configurable in the future.  If you don't want to make it writeable, there is a rake command for building the binaries, which you could run as root.  

As for having the "same" bug, that bug is exactly what I fixed.  Can you make sure that you are using the testing branch?  In particular, look at:

```
redmine_git_hosting/lib/git_hosting/patches/git_adapter_patch.rb
```

It should have the following in the middle:

```
base.class_eval do
    class << self
        begin
            alias_method_chain :sq_bin, :sudo
            begin
                alias_method_chain :client_command, :sudo
            rescue Exception =>e
            end
        rescue Exception => e
            # Hm.... Might be Redmine version < 1.2 (i.e. 1.1). Try redefining GIT_BIN.
            GitHosting.logger.warn "Seems to be early version of Redmine(1.1?), try redefining GIT_BIN."
            Redmine::Scm::Adapters::GitAdapter::GIT_BIN = GitHosting::git_exec()
        end
end
```

The double-level begin/rescue structure is to catch that problem.  If it turns out that you are still getting the problem, can you send me the exact error message that you got from the testing branch (like you did for the master branch)?  Also, what is strange, is that my master branch should have the same issue with writing the bin directory as my testing branch.  (Note that I _don't_ mean Eric's master branch here, but rather my master branch!).  Also, my testing branch is not my master branch.... (sorry if this sounds basic, but the particular behavior you are getting doesn't make sense to me).

**Comment by anarcat** [comment]
Oh, I see, I did mess up: i wasn't using the right branch. Things seem to be working okay, thanks.

**Comment by kubitron** [comment]
Ah.  Does "Working okay" mean "Working well"?  I can push these changes to my master branch if you really think they are working.

**Comment by anarcat** [comment]
Yes, it is working well.

I am getting tons of other issues migrating away from the older gitosis integration, but that's a whole different story...

**Comment by kubitron** [comment]
Ok.  If you have any problems, let me know (submit new issue).  Also, if you have any suggestions about better places to put the custom shell-scripts, let me know (you clearly have an opinion on this :-).  I moved them from /tmp for the reasons mentioned above.  I suppose I could make them configurable, but then my selinux setup scripts would get more complex...

Happy hacking.

**Comment by kubitron** [comment]
I am assuming that things are still working for you.  I have removed the testing branch and pushed this fix to my master branch.  Could you please pull from the master branch?  Also, I am now claiming compatibility with the Redmine 1.1 release.  If you end up finding something to contradict this, please let me know.

**Comment by kubitron** [comment]
Say -- I just looked at your installation FAQ, and it suggests installing my "testing" branch.

As mentioned above, I migrated these changes to the master branch and removed "testing" (This is only a temporary branch that I use for testing out changes).  Make sure to update your FAQ...

**Comment by anarcat** [comment]
Yep, I know about the testing branch.

I will look at this again very soon now, and give you feedback on how to migrate from previous plugins.

**Comment by kubitron** [comment]
Say -- Anarcat -- are you still working with older versions of Redmine?  I'm curious if the 0.5.0x version (head of master) still works for you...
